### ISSUE TITLE
deleting inside a directory does not work. More likely related to the issue of path

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#13]

**Comment by ykowsar** [comment]
Deleting the last file inside the directory still throws error. It should try to load the parent directory

**Comment by madisonkeene** [comment]
This is broken because of the stupid progress bar... great.

**Comment by madisonkeene** [comment]
Now fixed - added block of code at FileOperationsFactory.java:168 to load the container after deleting. Bad thing is that it will only now load container after every delete (even if dir not empty) but probably too hard to do any other way. Can re-visit later if need be.
