### ISSUE TITLE
Public and private link are not shown

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#14]

**Comment by madisonkeene** [comment]
Also not working for s3

**Comment by madisonkeene** [comment]
utilities.js:256 Uncaught ReferenceError: gsFileMetadata is not defined
setClipBoard @ utilities.js:256
success @ utilities.js:234
c @ jquery.min.js:4
fireWith @ jquery.min.js:4
k @ jquery.min.js:6
r @ jquery.min.js:6

**Comment by madisonkeene** [comment]
Now fixed. Issue was a simple merge error - contents of function setClipBoard() in utilities.js was updated to new version but params being passed in to function weren't.
