### ISSUE TITLE
Creating sub directory returns error

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#15]

**Comment by madisonkeene** [comment]
java.lang.NullPointerException
    org.genomespace.datamanager.core.MountedFileProvider.updateDisplayPath(MountedFileProvider.java:61)
    org.genomespace.datamanager.core.MountedFileProvider.createDirectory(MountedFileProvider.java:108)
    org.genomespace.datamanager.core.FileManager.createDirectory(FileManager.java:213)
    org.genomespace.datamanager.resource.FileObjectResource.createDirectory(FileObjectResource.java:215)
    org.genomespace.datamanager.resource.FileObjectResource.createFileObject(FileObjectResource.java:154)
    sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:498)
    org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
    org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
    org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
    org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
    org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:402)
    org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:349)
    org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
    org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
    org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
    org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
    org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
    org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
    org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:382)
    org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:535)
    org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:483)
    org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:420)

**Comment by madisonkeene** [comment]
Issue was it was looking for /root/genomespace/.hidden to upload as a temp file, and it doesn't exist. Now changed to not rely on the underlying filesystem at all by creating the file in java's temp directory (i.e. `System.getProperty("java.io.tmpdir");`). (SwiftFileSystemProvider:869)

**Comment by madisonkeene** [comment]
Now fixed. Creating sub dirs inside sub dirs also works perfectly :)
