### ISSUE TITLE
Restarting tomcat causes  400 Bad Request error

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#17]
GET https://newgs-test3.ddns.net:8443/datamanager/v1.0/file//Home/swift:test/ 400 (Bad Request)

This is the error you get when you try and open a swift container after restarting tomcat. Happened after changes to read-write permissions in `@PUT` request (made by @ykowsar) 

**Temp fix: unmount and re-mount swift container***

**Comment by madisonkeene** [comment]
Every other kind of request to other swift URL's (e.g. /storage/maditest/swift/test) works still

**Comment by ykowsar** [comment]
If the password for swift is incorrect or missing it should create the swiftResetPassword jsp file from dm-webservice.

This will happen inside dm-core in the FileObjectResource.java file: function getFileObjectGeneric. 

The process starts by catching a HeaderParamException error which should come from swift part.

**Comment by madisonkeene** [comment]
Correct exception now being thrown. Response returning HTML but nothing happening with it client side

**Comment by madisonkeene** [comment]
Solution: Return a status code 403 Forbidden (instead of 200) and catch the error in listDirectory() in dm.js

**Comment by madisonkeene** [comment]
Now fixed
