### ISSUE TITLE
Remove ANDS items from menu And check code is non-existant in merge

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#24]

**Comment by madisonkeene** [comment]
And check code is non-existant in merge

**Comment by ykowsar** [comment]
CHECK POM FILES IN SPECIFIC

**Comment by ykowsar** [comment]
Check all the functionalities again.

I had to change a few parts in both FileOperation file and swiftfilesystemprovider.

In  FileOperationsFactory.java:168 I had to create a foreevr loop which I do not like we should find a better alternative

**Comment by madisonkeene** [comment]
re: file ops factory - have you changed the code since? that loop will definitely end... if not just add a condition to check when you are at container level and break.
