### ISSUE TITLE
Error on first login - could not retrieve data format converters

### ISSUE THREAD

**Issue by alonie** [gvlproject/genomespace#27]
Registration fine, but on first login got error message box: "Could not retrieve data format converters [object Object] error'
This is probably related to there being no list of data formats when adding a private tool?

**Comment by madisonkeene** [comment]
I imagine this will be cleared up when we merge with Broad - is this right @ykowsar ?

**Comment by ykowsar** [comment]
These will be solved when merged with broads. They are related to entities in database
