### ISSUE TITLE
Bug when adding private tool

### ISSUE THREAD

**Issue by alonie** [gvlproject/genomespace#29]
Adding private tool: no list of available formats (the list is empty). Does not seem to matter, the tool is successfully created - perhaps the list of formats just directs the a warning message?

**Comment by madisonkeene** [comment]
@ykowsar is this related to #27 ?

**Comment by ykowsar** [comment]
These will be solved when merged with broads. They are related to entities in database

**Comment by madisonkeene** [comment]
this is causing a javascript error meaning we can't send any data when we launch a tool. We need this for the sepsis demo. I think I've found a work around for now, but re-opening because long term we need to fix this. There's instructions in an email from marco.

**Comment by madisonkeene** [comment]
Now fixed in both GS's.
