### ISSUE TITLE
Launch new genomespace.genome.edu.au

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#34]
Launch new version of local GS.
Will require porting existing user accounts - might be worth launching on gs-dev first.
Also need to make sure google drive credentials are in appropriate config files (if needed)

**Comment by madisonkeene** [comment]
Also crucial for me to be able to give CDK to neil/wilson

**Comment by madisonkeene** [comment]
Machine created at 115.146.86.198

**Comment by madisonkeene** [comment]
...and gs-dev now points to that IP

**Comment by madisonkeene** [comment]
Things we need to do to finish this:
- [x] Launch a database machine
- [x] Install MongoDB on DB machine
- [x] Port over existing user info from old DB to new DB (I imagine we'll need to, but we can check num users we have and determine if we need to)
- [x] Copy the GS code over from the merge machine
- [x] Hook up the DB machine to the GS machine
- [x] Install SSL certs for domain (+ re-gen GS key)
- [x] Obtain and add GDrive credentials
- [x] Disable the whole home/username AWS default space thing
- [x] Make tomcat use 443 not 8443
- [x] Test all the things
- [x] Swap the domain over to the actual gs.genome.edu.au
- [x] Throw a party/go to the pub(Get drunk to the point that genomespace does not exist in the world anymore)/sleep for 10 years

**Comment by madisonkeene** [comment]
To remove the user's home directory -
in dm-core/src/main/java/org/genomespace/datamanager/core/FileManager.java, line 160, function listDirectory(String fileObjectPathString, String userId)

comment out all parts related to createUserHomeDirectory();

**Comment by madisonkeene** [comment]
We also most definitely need to port over the user info- we've had a decent number of registrations this year.

**Comment by madisonkeene** [comment]
the 443 vs 8443 thing: http://stackoverflow.com/questions/23272666/tomcat7-bind-to-port-80-fails-in-ubuntu-14-04lts

**Comment by madisonkeene** [comment]
Obtaining the google drive credentials (I'll properly document this later):

1) Enable the drive API
2) Under 'credentials' create a new Oauth2 ClientID
3) copy the details into the GS config file.
4) magic!

**Comment by nuwang** [comment]
@madiflannery Google Drive will also need to be tested with Galaxy import/export I guess. I wonder whether it works in a similar way to how GenomeSpace handles dropbox (i.e. proxied through S3)

**Comment by madisonkeene** [comment]
Yeah definitely needs to be tested, not 100% sure how it works - but I need to fix the upload issues i'm hitting at the moment first (nothing is uploading to any storage type through normal gs upload atm haha)

**Comment by madisonkeene** [comment]
New dev machine launched - will live at genomespace-au-dev.genome.edu.au once the DNS update propagates throughout the interwebs.

**Comment by madisonkeene** [comment]
All dropbox users have now been kicked off in preparation for the move from dev to prod.

**Comment by madisonkeene** [comment]
Copying email here for record:
I made a maintenance page for GS - https://github.com/madiflannery/genomespace_maintenance
Prod genomespace is taken down, I am upgrading dev to prod tomorrow (https://genomespace.genome.edu.au/)
GS-dev appears to be down when you visit it- but its actually still up if you go directly to GS urls.

I will get Simon to change the DNS tomorrow, then I’ll change the URL in the code, undo the maintenance page redirect and we are good to go! :)
