### ISSUE TITLE
genomespace mongodb ansible updates

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#41]
In file /etc/mongod.conf

uncommet port = 27017 add  genomespace ip to with a comma bind_ip = 127.0.0.1,<genomespace-ip>

make sure the ingress port in security group is open for the instance.

It is recommended to only allow the genomespace instance to talk to mongodb via 27017 port

**Comment by ykowsar** [comment]
add nohup ./activemq console & to the running part

**Comment by madisonkeene** [comment]
Closing b/c this is now in the ansible repo.
