### ISSUE TITLE
Deleting a swift directory using CDK is causing a 404 error

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#58]
`@DELETE` request to datamanager

**Comment by madisonkeene** [comment]
this is most likely a server-side issue.

**Comment by madisonkeene** [comment]
dmClient.delete(dmClient.getMetadata(containerPath+dirToMake));

**Comment by ykowsar** [comment]
Ok
Deleting a directory has  not been built at all for CDK. Inside the GUI there is a whole new mechanism that delete a directory through a post request on fileop which we need to build from the scratch for the CDK :)

**Comment by ykowsar** [comment]
in cdk->DataMangerClientImpl replace line 1125 to:
//this.builder(FILES_SEGMENT, gsRemoteFilePath).delete(String.class);
Form form = new Form();
form.param("target", gsRemoteFilePath);
form.param("recursive", "true");
Response r =this.builder("fileops/delete").post(Entity.entity(form,MediaType.APPLICATION_FORM_URLENCODED_TYPE));
