### ISSUE TITLE
Tool icons arent uploading

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#60]
401 unauthorized

**Comment by madisonkeene** [comment]
The culprit, in CustomToolIconServlet.java - `if (iconDirMetadata == null)  iconDirMetadata = dm.createDirectory("/Home/"+gsUsername, "PrivateToolIcons");`

**Comment by madisonkeene** [comment]
I've hacked around this for now by disabling the servlet-url mapping in web.xml so it goes looking in a folder on the server... we need to figure something out long term for this.

**Comment by madisonkeene** [comment]
Solution: create a swift container and use that

**Comment by madisonkeene** [comment]
@ykowsar can you please document what you changed for this (or just email it to me) so I can reproduce on dev? :)

**Comment by ykowsar** [comment]
Ooops sorry I forgot to leave the comment. Change the web.xml in JSUI
bundle and remove two parts
1- The part related to toolIcon servlet and
2- Two relations related to toolIcon servlet.

It was weird that the relations and the servlet where one relation
apart. The servlet part is commented accordingly.

In the JSUI gui
I commented out this part:



 from the the form with the id: customIconUpload.

I think it was in the gsui.html

Cheers
Y

**Comment by madisonkeene** [comment]
Madi's To-do:
- [x]  Move gvl.png into jsui/toolicon/Galaxy-QLD-Splash.png
- [x]  Test new build system (i.e. that the icons actually copy into jsui webapps folder)
- [x]  Disable servlet on gs-dev
