### ISSUE TITLE
not showing the segments' path inside genomespace may result in not showing the end user some of the files.

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#67]
People can select any path as the path for segments and if the path is the same name with the file but with multiple level of hierarchy from swift point of view everything is fine but ...

**Comment by madisonkeene** [comment]
That issue description made no sense hahaha 😂  is this the issue where if its not like `segments_dir/<actual_segments>` and instead it has for eg `segments_dir/dir2/dir3/<actual_segments>` , swift itself is OK but GenomeSpace won't hide the segments?

**Comment by ykowsar** [comment]
Yes. Exactly :D

On Thu, Nov 24, 2016 at 11:35 AM, Madison Flannery <notifications@github.com

**Comment by madisonkeene** [comment]
Can we somehow use the info under the section `Retrieving a large object` from http://docs.openstack.org/developer/swift/overview_large_objects.html

specifically the part where you can grab the manifest itself?

**Comment by madisonkeene** [comment]
Theoretically that works but speed-wise I don't imagine it's great?

**Comment by madisonkeene** [comment]
Is the verdict that we're closing this? and documenting it?
