### ISSUE TITLE
Give madi access to GS repo on bitbucket

### ISSUE THREAD

**Issue by madisonkeene** [gvlproject/genomespace#7]
Email Marco

**Comment by madisonkeene** [comment]
@ykowsar reminder to do this please :)

**Comment by madisonkeene** [comment]
@ykowsar another reminder to do this asap (if you have please move to in progress so I know)

**Comment by ykowsar** [comment]
Sorry, flat out with submissions. Just wrote the email :) but what is your bitbucket account?

**Comment by madisonkeene** [comment]
https://bitbucket.org/madisonflannery/

**Comment by ykowsar** [comment]
Done!
