### ISSUE TITLE
Upload does not show the progress bar

### ISSUE THREAD

**Issue by ykowsar** [gvlproject/genomespace#9]
GenomeSpace now has a new progress bar. I have deliberately removed our own to make it more compatible. We need to apply GenomeSpace one.

**Comment by madisonkeene** [comment]
@ykowsar were you going to email Marco about this? If yes, this is your reminder :)

**Comment by ykowsar** [comment]
Tnx for the reminder :). Email sent!

**Comment by madisonkeene** [comment]
from Marco: "I straightened out the percent progress issue by changing line 40 on swiftUploader.js. I just took out the  + character. The progress event will include the total bytes uploaded each time, so no need to keep an accumulator variable."

**Comment by madisonkeene** [comment]
Now in issue #37
